[project]
dependencies = [
  "pillow==12.0.0",
  "selenium==4.38.0",
  "typing-extensions==4.15.0",
]
description = "Capture screenshot and/or HTML source code data of any given webpage and print it to stdout."
name = "take_a_shot"
readme = "README.md"
requires-python = ">=3.13"
version = "0.0.1"
